# Generated by Django 4.1.1 on 2022-09-10 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_details',
            new_name='CustomerDetails',
        ),
    ]
