# Generated by Django 4.1.1 on 2022-09-08 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('price_not', models.IntegerField(default=999)),
                ('desc', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default='0')),
                ('pub_date', models.DateField(auto_now=True)),
                ('image1', models.ImageField(default='', null=True, upload_to='products/images')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_email', models.CharField(default=None, max_length=100)),
                ('seller_password', models.CharField(default=None, max_length=100)),
                ('seller_contact', models.CharField(max_length=13)),
                ('seller_address', models.CharField(default=None, max_length=100)),
                ('seller_areapin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellers.seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
