# Generated by Django 4.1.1 on 2022-09-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pub_date',
            new_name='created_date',
        ),
    ]
