# Generated by Django 4.1.1 on 2022-09-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_alter_variation_variation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='category',
            new_name='varname',
        ),
    ]
