# Generated by Django 4.1.1 on 2022-09-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_cat_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='subcategory',
        ),
    ]
