# Generated by Django 4.1.1 on 2022-09-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
